projet_cpp/exo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('exercices/', views.ExerciceListView.as_view(), name='exercices'),
    path('exercice/<int:exercice_id>', views.detail, name='exercice-details'),
    
]

projet_cpp/projet_cpp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projet_cpp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

projet_cpp/exo/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager
from django.urls import reverse


class Chapitre(models.Model):
    annee = models.CharField(max_length=2, choices = [('1A', 'Première année'),('2A', 'Deuxième année')])
    matiere = models.CharField(max_length=2, choices = [('M', 'Maths'),('C',
        'Chimie'), ('P', 'Physique')])
    nom = models.CharField(max_length=200, null=False)


class Exercice(models.Model):
    nom = models.CharField(max_length=200, null=False)
    tags = TaggableManager()
    chapitre = models.ForeignKey(Chapitre, on_delete = models.CASCADE)

    def get_absolute_url(self):
        return reverse('exercice-details', args=[str(self.id)])


class Fichier(models.Model):
    file = models.FileField(upload_to='')
    format = models.CharField(max_length = 2, choices = [('w', 'Document Word'),
        ('p', 'PDF'), ('t', 'LaTeX'), ('i', 'Image')])
    exercice = models.ForeignKey(Exercice, related_name = 'fichier',
        on_delete = models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def ajouter(self): #fonction qui permettra d'ajouter des exos
        self.published_date = timezone.now()
        self.save()

    #def supprimer(self): #fonction qui permettra de supprimer des exos


    #def __str__(self):
    #    return self.title


class Utilisation(models.Model):
    date = models.DateTimeField()
    type = models.CharField(max_length = 200, null = False)
    exercice = models.ForeignKey(Exercice, related_name = 'utilisation',
        on_delete = models.CASCADE)
    correction = models.BooleanField()

projet_cpp/exo/forms.py
from django import forms

projet_cpp/exo/views.py
from django.shortcuts import render
from .models import Exercice, Chapitre, Fichier, Utilisation
from django.views import generic
from django.shortcuts import get_object_or_404

def home(request):
    return render(request, 'exo/home.html', {})

class ExerciceListView(generic.ListView):
    model = Exercice
    paginate_by = 10

def detail(request, exercice_id):
    exercice = get_object_or_404(Exercice, pk=exercice_id)
    return render(request, 'exo/detail.html', {'exercice': exercice,
    	'fichiers': Fichier.objects.filter(exercice_id=exercice_id)})

projet_cpp/exo/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Catalogue d'exercices</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com"> 
  <link href="https://fonts.googleapis.com/css2?family=Acme&family=Caveat:wght@600&family=Courgette&family=Cuprum:wght@500&family=Montserrat:wght@500&family=Roboto&display=swap" rel="stylesheet">
  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="page-header">
      <div class="wrapper col1">
        <div id="topbar">
          <div id="search">
            <form action="#" method="post">
              <fieldset>
                <input type="text" value="Rechercher un exercice&hellip;"  onfocus="this.value=(this.value=='Rechercher un exercice&hellip;')? '' : this.value ;" />
                <input type="submit" name="go" id="go" value="Recherche" />
              </fieldset>
            </form>
          </div>
        </div>
      </div>
      <h1><a href="/">ExoCpp</a></h1>
      <h5>Le site d'exercices de la Prépa des INP de Grenoble</h5>
      <!--<div class="annee">
        <p><a href="/">1A</a>
        <a href="/">2A</a></p>
      </div>-->
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
            <!--<p><h4><a href="{% url 'home' %}">Maths</a></h4></p>
            <p><h4><a href="{% url 'home' %}">Physique</a></h4></p>
            <p><h4><a href="{% url 'home' %}">Chimie</a></h4></p>-->
          <ul>
            {% block sidebar %}
              <li><h4><a href="{% url 'home' %}">Accueil</a></h4></li>
              <li><h4><a href="{% url 'exercices' %}">Tous les exercices</a></h4></li>
            {% endblock %}
            <li><h4><a href="#">1A</a></h4>
              <ul>
                <li><p><h4><a href="#">Maths</a></h4></p>
            <div class="liste-chap">
              <ul>
                <li><a href="#">Logique</a></li>
                <li><a href="#">Analyse</a></li>
                <li><a href="#">Suites</a></li>
              </ul>
            </div></li>
                <li><p><h4><a href="#">Physique</a></h4></p>
                <div class="liste-chap">
                  <ul>
                    <li><a href="#">CE1</a></li>
                    <li><a href="#">Méca1</a></li>
                    <li><a href="#">Thermo1</a></li>
                  </ul>
                </div></li>
                <li><p><h4><a href="#">Chimie</a></h4></p>
            <div class="liste-chap">
              <ul>
                <li><a href="#">Chimie Théorique</a></li>
                <li><a href="#">Chimie des solutions</a></li>
                <li><a href="#">Chimie Organique I</a></li>
              </ul>
            </div></li>
              </ul>
              </li>
            <li><h4><a href="#">2A</a></h4>
              <ul>
                <li><p><h4><a href="#">Maths</a></h4></p>
            <div class="liste-chap">
              <ul>
                <li><a href="#">Courbes paramétrées</a></li>
                <li><a href="#">Intégrales généralisées</a></li>
                <li><a href="#">Réduction des endomorphismes</a></li>
              </ul>
            </div></li>
                <li><p><h4><a href="#">Physique</a></h4></p>
                <div class="liste-chap">
                  <ul>
                    <li><a href="#">TTT</a></li>
                    <li><a href="#">POM</a></li>
                  </ul>
                </div></li>
                <li><p><h4><a href="#">Chimie</a></h4></p>
            <div class="liste-chap">
              <ul>
                <li><a href="#">Thermo/Cinétique II</a></li>
                <li><a href="#">Chimie Organique II</a></li>
              </ul>
            </div></li>
              </ul>
              </li>       
          </ul>
          <!--<p><h4><a href="#">Maths</a></h4></p>
            <div class="liste-chap">
              <ul>
                <li><a href="#">Courbes paramétrées</a></li>
                <li><a href="#">Intégrales généralisées</a></li>
                <li><a href="#">Réduction des endomorphismes</a></li>
              </ul>
            </div>
          <p><h4><a href="#">Physique</a></h4></p>
          <p><h4><a href="#">Chimie</a></h4></p>-->
      </div>
         <div class="col-sm-10 ">
             {% block content %}
             {% endblock %}
             {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">précédent</a>
                            {% endif %}
                            <span class="page-current">
                                Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">suivant</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
              {% endblock %} 
         </div>
    </div>
  </div>
</body>
</html>

projet_cpp/exo/templates/exo/base_0.html
{% extends 'base.html' %}

{% block titre %}
	Élève
{% endblock %}

{% block contenu %}
	<h1> {{ exercice.nom }} </h1>

	{{ exercice.chapitre.nom }}
	{ % for file un exercice.fichiers.all %}
		{% if file.format == "i" %}
			<img src="{{ file.file.url }}">
		{% else %}
			<a href="{{ file.file.url }}">{{ file.get_tyoe_display }}</a>
		{% endif %}}
	{% endfor %}

{% endblock %}

projet_cpp/exo/templates/exo/detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{exercice.nom}} ({{exercice.chapitre.nom}})</h1>
  <ul>
    {% for fichier in fichiers %}
		{% if fichier.format == "i" %}
			<img src="{{ fichier.file.url }}" alt="énoncé"/>
		{% else %}
			<a href="{{ fichier.download }}">{{ fichier.get_format_display }}</a>
		{% endif %}
	{% endfor %}
  </ul>
  
{% endblock %}

projet_cpp/exo/templates/exo/exercice_list.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
  <h1>Liste des exercices</h1>
  {% if exercice_list %}
  <ul>
    {% for exercice in exercice_list %}
      <li>
        <a href="{{ exercice.get_absolute_url }}">{{ exercice.nom }}</a> ({{exercice.chapitre.nom }})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Il n'y a pas d'exercices dans le catalogue.</p>
  {% endif %} 
{% endblock %}

projet_cpp/exo/templates/exo/home.html
{% extends 'base_generic.html' %}

{% block content %}
	<h1>ExoCpp</h1>
  	<p>Bienvenue sur ExoCpp ! Ici vous trouverez votre bonheur (enfin, au moins des exercices).</p>
{% endblock %}